voice_group dppt_voicegroup191
	voice_directsound 60, 0, DirectSoundWaveData_dp_reverscyn_16, 255, 0, 255, 16
	voice_keysplit_all voicegroup_dppt_voicegroup192				 @ drums 1
	voice_keysplit voicegroup_dppt_voicegroup195, keysplit_KeySplitTable6     @ piano
	voice_keysplit voicegroup_dppt_voicegroup196, keysplit_KeySplitTable7     @ piano low
	voice_keysplit voicegroup_dppt_voicegroup197, keysplit_KeySplitTable8     @ ep 1
	voice_keysplit voicegroup_dppt_voicegroup198, keysplit_KeySplitTable9     @ ep 2
	voice_keysplit_all voicegroup_dppt_voicegroup193				 @ drums 2
	voice_keysplit voicegroup_dppt_voicegroup199, keysplit_KeySplitTable10    @ clavi
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 42, 0, 57, 192
	voice_directsound 60, 0, DirectSoundWaveData_dp_glocken_c6_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 205
	voice_keysplit voicegroup_dppt_voicegroup200, keysplit_KeySplitTable11    @ vibraphone
	voice_keysplit voicegroup_dppt_voicegroup201, keysplit_KeySplitTable12    @ marimba
	voice_keysplit voicegroup_dppt_voicegroup202, keysplit_KeySplitTable13    @ xylophone
	voice_keysplit voicegroup_dppt_voicegroup203, keysplit_KeySplitTable14    @ tubular bell
	voice_keysplit voicegroup_dppt_voicegroup204, keysplit_KeySplitTable15    @ trinity piano
	voice_keysplit_all voicegroup_dppt_voicegroup194				 @ synth kick + snare
	voice_keysplit voicegroup_dppt_voicegroup205, keysplit_KeySplitTable16    @ rotary organ
	voice_keysplit voicegroup_dppt_voicegroup206, keysplit_KeySplitTable17    @ straight organ
	voice_directsound 60, 0, DirectSoundWaveData_dp_org5_c3_16, 255, 175, 235, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 200, 255, 171
	voice_keysplit voicegroup_dppt_voicegroup207, keysplit_KeySplitTable18    @ accordion
	voice_directsound 60, 0, DirectSoundWaveData_dp_harmonica_c3_16, 67, 247, 191, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_fretnoise60, 255, 0, 255, 16
	voice_keysplit voicegroup_dppt_voicegroup208, keysplit_KeySplitTable19    @ acoustic guitar
	voice_directsound 60, 0, DirectSoundWaveData_dp_bluesgt_a2_16, 255, 255, 227, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_eternaguitar36, 255, 253, 159, 208
	voice_keysplit voicegroup_dppt_voicegroup209, keysplit_KeySplitTable20    @ clean guitar
	voice_directsound 60, 0, DirectSoundWaveData_dp_spearpillarwind60, 255, 0, 255, 32
	voice_keysplit voicegroup_dppt_voicegroup210, keysplit_KeySplitTable21    @ distortion guitar 1
	voice_keysplit voicegroup_dppt_voicegroup211, keysplit_KeySplitTable22    @ power guitar
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0
	voice_keysplit voicegroup_dppt_voicegroup212, keysplit_KeySplitTable23    @ upright bass 1
	voice_directsound 60, 0, DirectSoundWaveData_dp_sting_bass_e1_16, 255, 251, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_pickbass_e1_16, 255, 251, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_fretlessbass_d1_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_g1_16, 255, 0, 255, 222
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 216
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass1_c2_16, 255, 42, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 222
	voice_keysplit voicegroup_dppt_voicegroup213, keysplit_KeySplitTable24    @ violin
	voice_directsound 60, 0, DirectSoundWaveData_dp_oct_g3_16, 255, 235, 255, 212
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 252, 0, 96
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 37, 244, 155, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_explosion, 37, 255, 0, 246
	voice_keysplit voicegroup_dppt_voicegroup214, keysplit_KeySplitTable25    @ pizzicato
	voice_keysplit voicegroup_dppt_voicegroup215, keysplit_KeySplitTable26    @ harp
	voice_keysplit voicegroup_dppt_voicegroup216, keysplit_KeySplitTable27    @ timpani 1
	voice_keysplit voicegroup_dppt_voicegroup217, keysplit_KeySplitTable28    @ strings
	voice_directsound 60, 0, DirectSoundWaveData_dp_octlow_cs2_16, 255, 200, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_octlowbra_b2_16, 255, 200, 255, 226
	voice_keysplit voicegroup_dppt_voicegroup218, keysplit_KeySplitTable27    @ timpani 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 250, 0, 220
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 250, 0, 171 @ shift up by 1 octave
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 150, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_octhit_c2_16, 255, 200, 255, 222
	voice_keysplit voicegroup_dppt_voicegroup219, keysplit_KeySplitTable29    @ trumpets 1
	voice_keysplit voicegroup_dppt_voicegroup220, keysplit_KeySplitTable30    @ trombone
	voice_keysplit voicegroup_dppt_voicegroup221, keysplit_KeySplitTable31    @ tuba
	voice_keysplit voicegroup_dppt_voicegroup222, keysplit_KeySplitTable29    @ trumpets 2
	voice_keysplit voicegroup_dppt_voicegroup223, keysplit_KeySplitTable9     @ french horns
	voice_keysplit voicegroup_dppt_voicegroup224, keysplit_KeySplitTable32    @ distortion guitar 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 224, 242, 101, 220
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_12, 224, 242, 101, 220
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass_c1_16, 255, 42, 255, 216
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 219, 252, 196
	voice_keysplit voicegroup_dppt_voicegroup225, keysplit_KeySplitTable23    @ upright bass 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 220
	voice_directsound 60, 0, DirectSoundWaveData_dp_oboe_c3_16, 255, 243, 127, 216
	voice_directsound 60, 0, DirectSoundWaveData_purenoise, 240, 242, 0, 182
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 58, 0, 101, 220
	voice_directsound 48, 0, DirectSoundWaveData_dp_sy_clarinet_c3_16, 255, 0, 127, 216
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 224, 242, 101, 182
	voice_keysplit voicegroup_dppt_voicegroup226, keysplit_KeySplitTable33    @ flute
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodpat_c4_16, 100, 247, 78, 136
	voice_directsound 60, 0, DirectSoundWaveData_dp_basschoir36, 255, 200, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_tenorchoir48, 255, 200, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_sopranochoir60, 255, 200, 255, 171
@	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 247, 78, 196			@ remaining voices wrap around
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy		@ to the next voice group, so
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 200, 255, 171			@ have some dittos
@	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 200, 255, 171
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
@	voice_keysplit voicegroup_dppt_voicegroup227, keysplit_KeySplitTable25    @ music box (platinum only)
@	voice_keysplit voicegroup_dppt_voicegroup228, keysplit_KeySplitTable34    @ banjo

voice_group dppt_voicegroup192
	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 247, 78, 196
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 200, 255, 171
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 200, 255, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_keysplit voicegroup_dppt_voicegroup227, keysplit_KeySplitTable25    @ music box (platinum only)
	voice_keysplit voicegroup_dppt_voicegroup228, keysplit_KeySplitTable34    @ banjo
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne1_roop, 255, 255, 191, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne2_loop, 255, 255, 191, 32
	voice_directsound 48, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 255, 16
	voice_directsound 60, 64, DirectSoundWaveData_dp_bass2, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_808snare_16, 255, 220, 0, 64
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr2_16, 255, 0, 255, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1_16, 255, 0, 255, 171
	voice_directsound 61, 58, DirectSoundWaveData_dp_rim1_roop, 255, 220, 0, 16
	voice_directsound 60, 64, DirectSoundWaveData_dp_oct_snare_16, 255, 0, 255, 0
	voice_directsound 60, 70, DirectSoundWaveData_dp_053clap, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_093snare, 255, 226, 127, 0
	voice_directsound 29, 30, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound 60, 80, DirectSoundWaveData_dp_closed_hihat_16, 255, 0, 227, 32
	voice_directsound 34, 40, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound 60, 80, DirectSoundWaveData_dp_pedalhight, 255, 0, 235, 16
	voice_directsound 41, 50, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound 60, 80, DirectSoundWaveData_dp_open_hihat_16, 255, 241, 0, 0
	voice_directsound 47, 100, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound 53, 107, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound 57, 64, DirectSoundWaveData_dp_cymbal1_16, 255, 246, 0, 214
	voice_directsound 55, 117, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 16
	voice_directsound 58, 30, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216
	voice_directsound 59, 20, DirectSoundWaveData_dp_china_cynbal, 255, 250, 0, 226
	voice_directsound 60, 30, DirectSoundWaveData_dp_ridecap, 255, 250, 0, 232
	voice_directsound 60, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 32
	voice_directsound 60, 84, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 226
	voice_directsound 60, 110, DirectSoundWaveData_dp_cawbell_16, 255, 0, 255, 176
	voice_directsound 60, 36, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216
	voice_directsound 61, 102, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216
	voice_directsound 60, 86, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216
	voice_directsound 60, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 176
	voice_directsound 57, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 176

	.align 2
voice_group dppt_voicegroup193 @ 
	voice_directsound 60, 20, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 176
	voice_directsound 60, 24, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 57, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 60, 26, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 60, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 60, 26, DirectSoundWaveData_dp_cabassa_16, 255, 243, 127, 176
	voice_directsound 60, 100, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 176
	voice_directsound 60, 98, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 63, 102, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 60, 25, DirectSoundWaveData_dp_india_per_16, 255, 0, 255, 16
	voice_directsound 60, 112, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 57, 100, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 55, 34, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 52, 22, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 59, 34, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 56, 90, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 54, 20, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 0
	voice_directsound 60, 107, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 0
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 200, 0, 0
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 249, 0, 196
	voice_directsound 60, 90, DirectSoundWaveData_dp_sheiker, 255, 243, 111, 64
	voice_directsound 60, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound 70, 26, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 54, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 65, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 60, 20, DirectSoundWaveData_dp_castanet_22, 255, 0, 255, 176
	voice_directsound 60, 20, DirectSoundWaveData_dp_kaaroop_16, 255, 255, 191, 238
	voice_directsound 48, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 255, 16
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr2_16, 255, 0, 255, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1_16, 255, 0, 255, 176
	voice_directsound 60, 64, DirectSoundWaveData_dp_oct_snare_16, 255, 0, 255, 0
	voice_directsound 60, 70, DirectSoundWaveData_dp_053clap, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_093snare, 255, 228, 127, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1, 255, 0, 227, 32
	voice_directsound 60, 58, DirectSoundWaveData_dp_808snare_16, 255, 222, 0, 64
	voice_directsound 60, 64, DirectSoundWaveData_dp_bass2, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_bassdr1, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_rim1_roop, 255, 255, 191, 16
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne1_roop, 255, 255, 191, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 32
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne2_loop, 255, 255, 191, 32
	voice_directsound 48, 30, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound 60, 82, DirectSoundWaveData_dp_closehight_16, 255, 0, 227, 32
	voice_directsound 53, 40, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound 60, 82, DirectSoundWaveData_dp_pedalhight, 255, 0, 227, 32
	voice_directsound 60, 50, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound 60, 82, DirectSoundWaveData_dp_openhight, 254, 235, 0, 32
	voice_directsound 66, 90, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound 72, 100, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound 57, 64, DirectSoundWaveData_dp_cymbal1_16, 255, 247, 0, 216
	voice_directsound 74, 110, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 16
	voice_directsound 58, 30, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216

	.align 2
voice_group dppt_voicegroup194 @ 
	voice_directsound 59, 20, DirectSoundWaveData_dp_china_cynbal, 255, 250, 0, 226
	voice_directsound 60, 30, DirectSoundWaveData_dp_ridecap, 255, 250, 0, 232
	voice_directsound 60, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 32
	voice_directsound 58, 84, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 226
	voice_directsound 60, 110, DirectSoundWaveData_dp_cawbell_16, 255, 0, 255, 176
	voice_directsound 60, 36, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216
	voice_directsound 61, 102, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216
	voice_directsound 60, 86, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216
	voice_directsound 60, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 176
	voice_directsound 57, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 176
	voice_directsound 60, 20, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 176
	voice_directsound 60, 24, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 57, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 60, 26, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 60, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound 60, 26, DirectSoundWaveData_dp_cabassa_16, 255, 243, 127, 176
	voice_directsound 60, 100, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 176
	voice_directsound 60, 98, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 63, 102, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound 60, 25, DirectSoundWaveData_dp_india_per_16, 255, 0, 255, 16
	voice_directsound 60, 112, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 57, 100, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 55, 34, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 52, 22, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound 59, 34, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 56, 90, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 57, 90, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 58, 90, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 200, 0, 0
	voice_directsound 60, 44, DirectSoundWaveData_dp_triangle_16, 255, 249, 0, 196
	voice_directsound 60, 90, DirectSoundWaveData_dp_sheiker, 255, 243, 111, 64
	voice_directsound 60, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound 61, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound 62, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound 63, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound 60, 94, DirectSoundWaveData_dp_castanet_22, 255, 0, 255, 176
	voice_directsound 60, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 255, 171
	voice_directsound 61, 64, DirectSoundWaveData_dp_synthkick, 255, 0, 255, 171
	voice_directsound 60, 64, DirectSoundWaveData_dp_synthsnare, 255, 0, 255, 0

	.align 2
voice_group dppt_voicegroup195 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_g1_16, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c2_16, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c3_16, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_g3_16, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c4_16, 255, 248, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_f4_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c5_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c6_16, 255, 247, 0, 208

	.align 2
voice_group dppt_voicegroup196 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c0_16, 255, 249, 0, 229
	voice_directsound 60, 0, DirectSoundWaveData_dp_sty_piano_c1_16, 255, 249, 0, 226

	.align 2
voice_group dppt_voicegroup197 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia_c3_22, 255, 243, 0, 32
	voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia_c4_22, 255, 243, 0, 32

	.align 2
voice_group dppt_voicegroup198 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia2_c3_22, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_el_pia2_c4_22, 255, 249, 0, 208

	.align 2
voice_group dppt_voicegroup199 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_clavi_c1_16, 255, 249, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_clavi_c2_16, 255, 249, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_clavi_c3_16, 255, 249, 0, 16

	.align 2
voice_group dppt_voicegroup200 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c1_16, 255, 247, 0, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c2_16, 255, 247, 0, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c3_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c4_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c5_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_vibra_c6_16, 255, 247, 0, 208

	.align 2
voice_group dppt_voicegroup201 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_marin_c3_16, 255, 247, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_dp_marin_c4_16, 255, 247, 0, 216
	voice_directsound 60, 0, DirectSoundWaveData_dp_marin_c5_16, 255, 247, 0, 216

	.align 2
voice_group dppt_voicegroup202 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c2_16, 255, 249, 25, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c3_16, 255, 249, 25, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c4_16, 255, 249, 57, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c5_16, 255, 249, 57, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_xylphone_c6_16, 255, 247, 25, 196

	.align 2
voice_group dppt_voicegroup203 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_tub_bell_c3_16, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_tub_bell_c4_16, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_tub_bell_c5_16, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_tub_bell_c6_16, 255, 249, 0, 226

	.align 2
voice_group dppt_voicegroup204 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano36, 255, 249, 0, 226
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano48, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano60, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinitypiano72, 255, 248, 0, 208

	.align 2
voice_group dppt_voicegroup205 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c2_16, 255, 0, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c3_16, 255, 200, 227, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c4_16, 255, 0, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org1_c5_16, 255, 0, 255, 208

	.align 2
voice_group dppt_voicegroup206 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_org4_c3_16, 255, 0, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_org4_c4_16, 255, 0, 255, 208

	.align 2
voice_group dppt_voicegroup207 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c1_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c2_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c3_16, 100, 200, 217, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_accordion_c4_16, 81, 200, 191, 196

	.align 2
voice_group dppt_voicegroup208 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e1_16, 255, 253, 127, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e2_16, 255, 253, 127, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e3_16, 255, 253, 127, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_acgt_e4_16, 255, 253, 127, 208

	.align 2
voice_group dppt_voicegroup209 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_clean_gt_c1_16, 255, 247, 0, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_clean_gt_c2_16, 255, 247, 0, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_clean_gt_c3_16, 255, 247, 0, 176

	.align 2
voice_group dppt_voicegroup210 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e1_16, 255, 253, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_c2_16, 255, 253, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e3_16, 255, 253, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_e4_16, 255, 253, 0, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_disgt_b4_16, 255, 253, 0, 16

	.align 2
voice_group dppt_voicegroup211 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_power_gt_e1_16, 255, 251, 127, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_power_gt_b1_16, 255, 251, 127, 16
	voice_directsound 60, 0, DirectSoundWaveData_dp_power_gt_e2_16, 255, 251, 127, 16

	.align 2
voice_group dppt_voicegroup212 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_g1_16, 255, 251, 0, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_gs2_16, 255, 251, 0, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 251, 0, 176

	.align 2
voice_group dppt_voicegroup213 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c1_16, 100, 243, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c3_16, 100, 247, 255, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c4_16, 67, 247, 118, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_violin_c5_16, 45, 247, 78, 208

	.align 2
voice_group dppt_voicegroup214 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_pic_g4_16, 255, 235, 159, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_pic_g5_16, 255, 228, 159, 188

	.align 2
voice_group dppt_voicegroup215 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_harp_c3_16, 255, 249, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_harp_c4_16, 255, 247, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_harp_c5_16, 255, 243, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_harp_c6_16, 255, 235, 0, 196

	.align 2
voice_group dppt_voicegroup216 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_e_16, 255, 248, 0, 205
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_as_16, 255, 248, 0, 205

	.align 2
voice_group dppt_voicegroup217 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c1_16, 255, 243, 227, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c2_16, 255, 240, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c3_16, 135, 235, 159, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_strings_c4_16, 135, 225, 127, 208

	.align 2
voice_group dppt_voicegroup218 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_merotim_c2_16, 255, 250, 0, 212
	voice_directsound 60, 0, DirectSoundWaveData_dp_merotim_c3_16, 255, 250, 0, 212

	.align 2
voice_group dppt_voicegroup219 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_cs3_16, 255, 243, 101, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_cs4_16, 255, 243, 101, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_b4_16, 255, 235, 101, 208

	.align 2
voice_group dppt_voicegroup220 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_trombone_c2_16, 255, 243, 159, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trombone_c3_16, 255, 243, 159, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_trombone_c4_16, 255, 243, 159, 208

	.align 2
voice_group dppt_voicegroup221 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_tuba_c1_22, 255, 0, 252, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_tuba_c2_22, 255, 0, 252, 196

	.align 2
voice_group dppt_voicegroup222 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_cs3_16, 255, 243, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_cs4_16, 255, 243, 191, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_tp_b4_16, 255, 235, 191, 208

	.align 2
voice_group dppt_voicegroup223 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_f_horn_c2_16, 62, 219, 219, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_f_horn_c4_16, 255, 219, 255, 208

	.align 2
voice_group dppt_voicegroup224 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c1_16, 255, 247, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c2_16, 255, 247, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c3_16, 255, 247, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c4_16, 255, 247, 255, 176

	.align 2
voice_group dppt_voicegroup225 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_g1_16, 255, 0, 255, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_gs2_16, 255, 0, 255, 176
	voice_directsound 60, 0, DirectSoundWaveData_dp_woodbass_d3_16, 255, 0, 255, 176

	.align 2
voice_group dppt_voicegroup226 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_flute_c4_16, 255, 247, 159, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_flute_c5_16, 255, 247, 127, 196
	voice_directsound 60, 0, DirectSoundWaveData_dp_flute_c6_16, 255, 247, 71, 196

	.align 2
voice_group dppt_voicegroup227 @ 
	voice_directsound 60, 0, DirectSoundWaveData_pl_musicbox62, 255, 250, 2, 236
	voice_directsound 60, 0, DirectSoundWaveData_pl_musicbox79, 255, 248, 2, 224

	.align 2
voice_group dppt_voicegroup228 @ 
	voice_directsound 60, 0, DirectSoundWaveData_dp_banjo48, 255, 243, 0, 208
	voice_directsound 60, 0, DirectSoundWaveData_dp_banjo60, 255, 243, 0, 208
