// Add new IDs here
enum {
    HELP_START_MENU,
    HELP_MEGA_EVOLUTION,
    HELP_MASTER_BALL,
    HELP_GIMMIGHOUL_COINS,
    HELP_EASY_MODE,
    HELP_NORMAL_MODE,
    HELP_HARD_MODE,
    HELP_LEVEL_CAP,
    HELP_MINIMAL_GRIND_MODE,
    HELP_POKE_BALL,
    HELP_LUNATIC_MODE,
    HELP_COUNT
};
