#ifndef GUARD_PSS_ICONS_CONST_H
#define GUARD_PSS_ICONS_CONST_H

enum pssicons {
    PSS_NONE,
    PSS_ICON_BARRY,
    PSS_ICON_HIKARI,
    PSS_ICON_REPORTER,
    PSS_ICON_MOM,
    PSS_ICON_SORCERER,
    PSS_ICON_LUCIEN,
    PSS_ICON_SCIENTIST,
    PSS_ICON_JOY,
    PSS_ICON_GIOVANNI,
};

#endif // GUARD_PSS_ICONS_CONST_H