gText_Birch_Welcome::
	.string "Hello, there!\n"
	.string "It's so very nice to meet you.\p"
	.string "Welcome to the world of Dark\n"
	.string "Worship 2!\p"
	.string "My name is Hikari.\p"
	.string "However, everyone just calls me\n"
	.string "the Pokémon Professor.\p"
	.string "Before we proceed, is this your\n"
	.string "first adventure?\p"
	.string "If you need advice, I'm certainly\n"
	.string "capable of giving it later.\p"
	.string "$"

gText_Birch_WelcomePt::
	.string "Olá!\n"
	.string "É um prazer enorme te conhecer.\p"
	.string "Bem-vindo ao mundo de\n"
	.string "Dark Worship 2!\p"
	.string "Meu nome é Hikari.\p"
	.string "No entanto, todos me chamam de\n"
	.string "Professora Pokémon.\p"
	.string "Antes de prosseguirmos, esta é a\n"
	.string "sua primeira aventura?\p"
	.string "Se você precisar de conselhos, com\n"
	.string "certeza poderei te ajudar depois.\p"
	.string "$"

gText_Birch_WelcomeEs::
	.string "¡Hola!\n"
	.string "Es un verdadero placer conocerte.\p"
	.string "¡Bienvenido al mundo de\n"
	.string "Dark Worship 2!\p"
	.string "Mi nombre es Hikari.\p"
	.string "Sin embargo, todos me llaman\n"
	.string "la Profesora Pokémon.\p"
	.string "Antes de continuar, ¿es esta tu\n"
	.string "primera aventura?\p"
	.string "Si necesitas consejos, con gusto\n"
	.string "podré ayudarte más adelante.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as Pokémon.\p"
	.string "We humans live alongside Pokémon\n"
	.string "as friends.\p"
	.string "At times we play together, and at\n"
	.string "other times we work together.\p"
	.string "Some people user their Pokémon to\n"
	.string "battle and develop closer bonds\l"
	.string "with them.\p"
	.string "What do I do?\p"
	.string "I conduct research so that we may\n"
	.string "learn more about Pokémon.\p"
	.string "$"

gText_Birch_MainSpeechPt::
	.string "Este mundo é amplamente habitado\n"
	.string "por criaturas conhecidas como\l"
	.string "Pokémon.\p"
	.string "Nós, humanos, vivemos ao lado dos\n"
	.string "Pokémon como amigos.\p"
	.string "Às vezes brincamos juntos, e em\n"
	.string "outras nós trabalhamos juntos.\p"
	.string "Algumas pessoas usam seus Pokémon\n"
	.string "para batalhar e criar laços mais\l"
	.string "fortes com eles.\p"
	.string "E eu? O que eu faço?\p"
	.string "Eu realizo pesquisas para que\n"
	.string "possamos aprender mais sobre os\l"
	.string "Pokémon.\p"
	.string "$"

gText_Birch_MainSpeechEs::
	.string "Este mundo está ampliamente\n"
	.string "habitado por criaturas conocidas\l"
	.string "como Pokémon.\p"
	.string "Nosotros, los humanos, vivimos\n"
	.string "junto a los Pokémon como amigos.\p"
	.string "A veces jugamos juntos, y otras\n"
	.string "veces trabajamos juntos.\p"
	.string "Algunas personas usan a sus\n"
	.string "Pokémon para luchar y fortalecer\l"
	.string "sus lazos con ellos.\p"
	.string "¿Y yo? ¿A qué me dedico?\p"
	.string "Realizo investigaciones para que\n"
	.string "podamos aprender más sobre los\l"
	.string "Pokémon.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, why don't you tell me a\n"
	.string "little bit about yourself?$"

gText_Birch_AndYouArePt::
	.string "Agora, por que você näo me conta\n"
	.string "um pouco sobre você?$"

gText_Birch_AndYouAreEs::
	.string "Ahora, ¿por qué no me cuentas\n"
	.string "un poco sobre ti?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_BoyOrGirlPt::
	.string "Você é um menino?\n"
	.string "Ou é uma menina?$"

gText_Birch_BoyOrGirlEs::
	.string "¿Eres un niño?\n"
	.string "¿O eres una niña?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_WhatsYourNamePt::
	.string "Tudo bem.\n"
	.string "Qual é o seu nome?$"

gText_Birch_WhatsYourNameEs::
	.string "Muy bien.\n"
	.string "¿Cuál es tu nombre?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_SoItsPlayerPt::
	.string "Entäo é {PLAYER}{KUN}?$"

gText_Birch_SoItsPlayerEs::
	.string "¿Entonces eres {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of PINEVEIL.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_YourePlayerPt::
	.string "Ah, ok!\p"
	.string "Entäo você é {PLAYER}{KUN}, que\n"
	.string "está se mudando para minha cidade\l"
	.string "natal de PINEVEIL.\l"
	.string "Agora entendi!\p"
	.string "$"

gText_Birch_YourePlayerEs::
	.string "¡Ah, está bien!\p"
	.string "Entonces eres {PLAYER}{KUN}, que\n"
	.string "se está mudando a mi ciudad natal\l"
	.string "de PINEVEIL.\l"
	.string "¡Ahora lo entiendo!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, {PLAYER}{KUN}, the time has\n"
	.string "come.\p"
	.string "Your very own tale of grand\n"
	.string "adventure is about to unfold.\p"
	.string "On your journey, you will meet\n"
	.string "countless Pokémon and People.\p"
	.string "I'm sure that along the way you\n"
	.string "will discover many things, perhaps\l"
	.string "even something about yourself.\p"
	.string "Now, go on, leap into the world of\n"
	.string "Pokémon.\p"
	.string "$"

gText_Birch_AreYouReadyPt::
	.string "Muito bem, {PLAYER}{KUN}, chegou a\n"
	.string "hora.\p"
	.string "Sua própria história de uma grande\n"
	.string "aventura está prestes a começar.\p"
	.string "Em sua jornada, você encontrará\n"
	.string "inúmeros Pokémon e pessoas.\p"
	.string "Tenho certeza de que, no caminho,\n"
	.string "você descobrirá muitas coisas,\l"
	.string "talvez até algo sobre si mesmo.\p"
	.string "Agora vá, mergulhe no mundo dos\n"
	.string "Pokémon.\p"
	.string "$"
	
gText_Birch_AreYouReadyEs::
	.string "Muy bien, {PLAYER}{KUN}, ha llegado la\n"
	.string "hora.\p"
	.string "Tu propia historia de una gran\n"
	.string "aventura está a punto de comenzar.\p"
	.string "En tu viaje, encontrarás\n"
	.string "innumerables Pokémon y personas.\p"
	.string "Estoy seguro de que, en el camino,\n"
	.string "descubrirás muchas cosas, tal vez\l"
	.string "incluso algo sobre ti mismo.\p"
	.string "Ahora ve, sumérgete en el mundo de\n"
	.string "los Pokémon.\p"
	.string "$"

