gText_HowMayIServeYou::
	.string "Welcome!\p"
	.string "How may I serve you?$"

gText_PleaseComeAgain::
	.string "Please come again!$"

gText_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{STRING 5}, welcome!\p"
	.string "What can I do for you?$"

// Português
gText_HowMayIServeYouPt::
	.string "Bem-vindo!\p"
	.string "Como posso ajudá-lo?$"

gText_PleaseComeAgainPt::
	.string "Volte sempre!$"

gText_PlayerWhatCanIDoForYouPt::
	.string "{PLAYER}{STRING 5}, bem-vindo!\p"
	.string "O que posso fazer por você?$"


// Español
gText_HowMayIServeYouEs::
	.string "¡Bienvenido!\p"
	.string "¿Cómo puedo ayudarle?$"

gText_PleaseComeAgainEs::
	.string "¡Vuelva pronto!$"

gText_PlayerWhatCanIDoForYouEs::
	.string "¡{PLAYER}{STRING 5}, bienvenido!\p"
	.string "¿Qué puedo hacer por usted?$"
