Questionnaire_Text_FillOut::
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"

Questionnaire_Text_FillOutPt::
	.string "Há um questionário.\n"
	.string "Gostaria de respondê-lo?$"

Questionnaire_Text_FillOutEs::
	.string "Hay un cuestionario.\n"
	.string "¿Quieres rellenarlo?$"

Questionnaire_Text_ThankYou::
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"

Questionnaire_Text_ThankYouPt::
	.string "Obrigado por dedicar seu tempo\n"
	.string "para responder ao nosso questionário.\p"
	.string "Sua opinião será usada como\n"
	.string "referência futura.$"

Questionnaire_Text_ThankYouEs::
	.string "Gracias por tomarte el tiempo de\n"
	.string "rellenar nuestro cuestionario.\p"
	.string "Tus comentarios se usarán como\n"
	.string "referencia futura.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY GIFT.\p"
	.string "From now on, you should be\n"
	.string "receiving MYSTERY GIFTS!$"

Questionnaire_Text_YouKnowThoseWordsGiftPt::
	.string "Ah, olá!\n"
	.string "Você conhece essas palavras?\p"
	.string "Isso significa que você deve saber\n"
	.string "sobre o PRESENTE MISTERIOSO.\p"
	.string "De agora em diante, você poderá\n"
	.string "receber PRESENTES MISTERIOSOS!$"

Questionnaire_Text_YouKnowThoseWordsGiftEs::
	.string "¡Ah, hola!\n"
	.string "¿Conoces esas palabras?\p"
	.string "Eso significa que debes saber\n"
	.string "sobre el REGALO MISTERIOSO.\p"
	.string "¡A partir de ahora podrás recibir\n"
	.string "REGALOS MISTERIOSOS!$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY GIFT.$"

Questionnaire_Text_YouCanAccessMysteryGiftPt::
	.string "Depois de salvar o jogo, você pode\n"
	.string "acessar o PRESENTE MISTERIOSO.$"

Questionnaire_Text_YouCanAccessMysteryGiftEs::
	.string "Cuando guardes la partida, podrás\n"
	.string "acceder al REGALO MISTERIOSO.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY EVENT.$"

Questionnaire_Text_YouKnowThoseWordsEventPt::
	.string "Ah, olá!\n"
	.string "Você conhece essas palavras?\p"
	.string "Isso significa que você deve saber\n"
	.string "sobre o EVENTO MISTERIOSO.$"

Questionnaire_Text_YouKnowThoseWordsEventEs::
	.string "¡Ah, hola!\n"
	.string "¿Conoces esas palabras?\p"
	.string "Eso significa que debes saber\n"
	.string "sobre el EVENTO MISTERIOSO.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY EVENT.$"

Questionnaire_Text_YouCanAccessMysteryEventPt::
	.string "Depois de salvar o jogo, você pode\n"
	.string "acessar o EVENTO MISTERIOSO.$"

Questionnaire_Text_YouCanAccessMysteryEventEs::
	.string "Cuando guardes la partida, podrás\n"
	.string "acceder al EVENTO MISTERIOSO.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Thank you for using the MYSTERY\n"
	.string "EVENT System.\p"
	.string "You must be {PLAYER}.\n"
	.string "There is a ticket here for you.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "It appears to be for use at\n"
	.string "the LILYCOVE CITY port.\p"
	.string "Why not give it a try and see what\n"
	.string "it is about?$"
