@ Starting from here, these movements are considered
@ 'safe' (won't put follower into a Pokeball)
Common_Movement_FollowerSafeStart::
Common_Movement_QuestionMark:
	emote_question_mark
	step_end

Common_Movement_QuestionMarkFacingUp:
	emote_question_mark
	face_up
	step_end

Common_Movement_ExclamationMark:
	emote_exclamation_mark
	step_end

Common_Movement_EmoteHeart:
	emote_heart
	step_end

Common_Movement_EmoteSmile:
	emote_smile
	step_end

Common_Movement_ExclaimFacingDown:
	emote_exclamation_mark
	face_down
	step_end

Common_Movement_ExclaimFacingUp:
	emote_exclamation_mark
	face_up
	step_end

Common_Movement_ExclaimFacingRight:
	emote_exclamation_mark
	face_right
	step_end

Common_Movement_ExclaimFacingLeft:
	emote_exclamation_mark
	face_left
	step_end

Common_Movement_Delay48:
	delay_16
	delay_16
	delay_16
	step_end

Common_Movement_FacePlayer:
	face_player
	step_end

Common_Movement_FaceAwayPlayer:
	face_away_player
	step_end

Common_Movement_FaceOriginalDirection:
	face_original_direction
	step_end

Common_Movement_WalkInPlaceFasterLeft:
	walk_in_place_faster_left
	step_end

Common_Movement_WalkInPlaceFasterUp:
	walk_in_place_faster_up
	step_end

Common_Movement_WalkInPlaceFasterRight:
	walk_in_place_faster_right
	step_end

Common_Movement_WalkInPlaceFasterDown:
	walk_in_place_faster_down
	step_end

Common_Movement_FaceRight::
	face_right
	step_end

Common_Movement_FaceLeft::
	face_left
	step_end

Common_Movement_FaceDown::
	face_down
	step_end

Common_Movement_FaceUp::
	face_up
	step_end

Common_Movement_WalkInPlaceUp:
	walk_in_place_up
	step_end

Common_Movement_WalkInPlaceDown:
	walk_in_place_down
	step_end

Common_Movement_WalkInPlaceLeft:
	walk_in_place_left
	step_end

Common_Movement_WalkInPlaceRight:
	walk_in_place_right
	step_end

@ End of follower-safe movements
Common_Movement_FollowerSafeEnd::
	step_end
	
Common_Movement_WalkUp5::
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp6:
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_WalkUp4:
	walk_up
	walk_up
	walk_up
	walk_up
	step_end

Common_Movement_Delay32:
	delay_16
	delay_16
	step_end

Common_Movement_WalkUp::
	walk_up
	step_end

@ Unused
Common_Movement_WalkUp2::
	walk_up
	walk_up
	step_end

@ Follower NPC
Common_Movement_WalkUpSlow::
	walk_slow_up
	step_end

Common_Movement_WalkDownSlow::
	walk_slow_down
	step_end

Common_Movement_WalkRightSlow::
	walk_slow_right
	step_end

Common_Movement_WalkLeftSlow::
	walk_slow_left
	step_end

Common_Movement_WalkDown::
	walk_down
	step_end

Common_Movement_WalkRight::
	walk_right
	step_end

Common_Movement_WalkLeft::
	walk_left
	step_end

Common_Movement_WalkUpFast::
	walk_fast_up
	step_end

Common_Movement_WalkDownFast::
	walk_fast_down
	step_end

Common_Movement_WalkRightFast::
	walk_fast_right
	step_end

Common_Movement_WalkLeftFast::
	walk_fast_left
	step_end

Common_Movement_WalkUpFaster::
	walk_faster_up
	step_end

Common_Movement_WalkDownFaster::
	walk_faster_down
	step_end

Common_Movement_WalkRightFaster::
	walk_faster_right
	step_end

Common_Movement_WalkLeftFaster::
	walk_faster_left
	step_end

Common_Movement_EmojiAngry::
	emoji_angry
	step_end

Common_Movement_EmojiBlush::
	emoji_blush
	step_end

Common_Movement_EmojiConfiant::
	emoji_confiant
	step_end

Common_Movement_EmojiConfident::
	emoji_confident
	step_end

Common_Movement_EmojiConfidentSmiling::
	emoji_confident_smiling
	step_end

Common_Movement_EmojiDoubt::
	emoji_doubt
	step_end

Common_Movement_EmojiGrin::
	emoji_grin
	step_end

Common_Movement_EmojiHeartEyes::
	emoji_heart_eyes
	step_end

Common_Movement_EmojiInnocent::
	emoji_innocent
	step_end

Common_Movement_EmojiJoy::
	emoji_joy
	step_end

Common_Movement_EmojiKissing::
	emoji_kissing
	step_end

Common_Movement_EmojiRelaxed::
	emoji_relaxed
	step_end

Common_Movement_EmojiRelivied::
	emoji_relivied
	step_end

Common_Movement_EmojiScream::
	emoji_scream
	step_end

Common_Movement_EmojiSlithly::
	emoji_slithly
	step_end

Common_Movement_EmojiSmiley::
	emoji_smiley
	step_end

Common_Movement_EmojiSob::
	emoji_sob
	step_end

Common_Movement_EmojiThinking::
	emoji_thinking
	step_end

Common_Movement_EmojiTongueWinking::
	emoji_tongue_winking
	step_end

Common_Movement_EmojiWink::
	emoji_wink
	step_end

Common_Movement_EmojiYum::
	emoji_yum
	step_end
